export const ADD_ITEM = 'ADD_ITEM'
export const DELETE_ITEM = 'DELETE_ITEM'
export const ADD_QUANTITY = 'ADD_QUANTITY'
export const CART_DETAIL = 'CART_DETAIL'
export const CART = 'CART'
export const CLEAR_CART_DATA = 'CLEAR_CART_DATA'